
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 07 13:06:22 CEST 2013
//----------------------------------------------------

package src.plg.proto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 10;
  public static final int DISTINTO = 42;
  public static final int CONSTS = 12;
  public static final int CABIERTO = 59;
  public static final int PABIERTO = 56;
  public static final int MULT = 44;
  public static final int GUIONBAJO = 67;
  public static final int CHAR = 49;
  public static final int CONST = 13;
  public static final int numeroReal = 6;
  public static final int NATURAL = 29;
  public static final int RESTA = 36;
  public static final int INTEGER = 28;
  public static final int INT = 50;
  public static final int subprograms = 18;
  public static final int DESPIZQ = 47;
  public static final int letra = 3;
  public static final int LLABIERTA = 61;
  public static final int MENORIGUAL = 39;
  public static final int IGUAL = 66;
  public static final int caracter = 5;
  public static final int ARROBA = 64;
  public static final int DIV = 45;
  public static final int SUMA = 43;
  public static final int subprogram = 19;
  public static final int numero = 9;
  public static final int IF = 26;
  public static final int ENDWHILE = 25;
  public static final int MAYORIGUAL = 40;
  public static final int var = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 27;
  public static final int ident = 2;
  public static final int TRUE = 31;
  public static final int COMILLA = 58;
  public static final int error = 1;
  public static final int COMA = 63;
  public static final int MENOR = 38;
  public static final int in = 33;
  public static final int MOD = 46;
  public static final int instructions = 11;
  public static final int DESPDER = 48;
  public static final int MAYOR = 37;
  public static final int numeroEnt = 7;
  public static final int CCERRADO = 60;
  public static final int PCERRADO = 57;
  public static final int ENDIF = 22;
  public static final int ELSE = 21;
  public static final int out = 34;
  public static final int tipo = 15;
  public static final int IGUALIGUAL = 41;
  public static final int WHILE = 23;
  public static final int vars = 16;
  public static final int FLOAT = 30;
  public static final int THEN = 20;
  public static final int not = 52;
  public static final int SWAP2 = 55;
  public static final int SWAP1 = 54;
  public static final int NAT = 51;
  public static final int numeroNat = 8;
  public static final int Call = 35;
  public static final int FALSE = 32;
  public static final int LLCERRADA = 62;
  public static final int tipos = 14;
  public static final int DP = 53;
  public static final int digito = 4;
  public static final int DO = 24;
  public static final int PYC = 65;
}

