
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 03 18:22:29 CEST 2013
//----------------------------------------------------

package src.plg.proto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 8;
  public static final int DISTINTO = 41;
  public static final int CONSTS = 10;
  public static final int CABIERTO = 58;
  public static final int PABIERTO = 55;
  public static final int MULT = 43;
  public static final int GUIONBAJO = 66;
  public static final int CHAR = 48;
  public static final int CONST = 11;
  public static final int numeroReal = 6;
  public static final int NATURAL = 27;
  public static final int RESTA = 35;
  public static final int INTEGER = 26;
  public static final int INT = 49;
  public static final int subprograms = 16;
  public static final int DESPIZQ = 46;
  public static final int letra = 3;
  public static final int LLABIERTA = 60;
  public static final int MENORIGUAL = 38;
  public static final int IGUAL = 65;
  public static final int caracter = 5;
  public static final int ARROBA = 63;
  public static final int DIV = 44;
  public static final int SUMA = 42;
  public static final int subprogram = 17;
  public static final int numero = 29;
  public static final int IF = 24;
  public static final int ENDWHILE = 23;
  public static final int MAYORIGUAL = 39;
  public static final int var = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 25;
  public static final int ident = 2;
  public static final int TRUE = 30;
  public static final int COMILLA = 57;
  public static final int error = 1;
  public static final int COMA = 62;
  public static final int MENOR = 37;
  public static final int in = 32;
  public static final int MOD = 45;
  public static final int instructions = 9;
  public static final int DESPDER = 47;
  public static final int MAYOR = 36;
  public static final int numeroEnt = 7;
  public static final int CCERRADO = 59;
  public static final int PCERRADO = 56;
  public static final int ENDIF = 20;
  public static final int ELSE = 19;
  public static final int out = 33;
  public static final int tipo = 13;
  public static final int IGUALIGUAL = 40;
  public static final int WHILE = 21;
  public static final int vars = 14;
  public static final int FLOAT = 28;
  public static final int THEN = 18;
  public static final int not = 51;
  public static final int SWAP2 = 54;
  public static final int SWAP1 = 53;
  public static final int NAT = 50;
  public static final int Call = 34;
  public static final int FALSE = 31;
  public static final int LLCERRADA = 61;
  public static final int tipos = 12;
  public static final int DP = 52;
  public static final int digito = 4;
  public static final int DO = 22;
  public static final int PYC = 64;
}

