
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 08 01:19:37 CEST 2013
//----------------------------------------------------

package src.plg.proto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 10;
  public static final int DISTINTO = 44;
  public static final int CONSTS = 12;
  public static final int TIPOS = 14;
  public static final int CABIERTO = 61;
  public static final int PABIERTO = 58;
  public static final int MULT = 46;
  public static final int GUIONBAJO = 69;
  public static final int CHAR = 51;
  public static final int CONST = 13;
  public static final int TIPO = 15;
  public static final int numeroReal = 6;
  public static final int INSTRUCTIONS = 11;
  public static final int SUBPROGRAM = 19;
  public static final int VARS = 16;
  public static final int NATURAL = 29;
  public static final int RESTA = 38;
  public static final int INTEGER = 28;
  public static final int INT = 52;
  public static final int DESPIZQ = 49;
  public static final int letra = 3;
  public static final int LLABIERTA = 63;
  public static final int MENORIGUAL = 41;
  public static final int AND = 37;
  public static final int IGUAL = 68;
  public static final int CARACTER = 5;
  public static final int OR = 36;
  public static final int ARROBA = 66;
  public static final int DIV = 47;
  public static final int SUMA = 45;
  public static final int numero = 9;
  public static final int IF = 26;
  public static final int ENDWHILE = 25;
  public static final int MAYORIGUAL = 42;
  public static final int EOF = 0;
  public static final int BOOLEAN = 27;
  public static final int ident = 2;
  public static final int TRUE = 31;
  public static final int COMILLA = 60;
  public static final int error = 1;
  public static final int COMA = 65;
  public static final int MENOR = 40;
  public static final int in = 33;
  public static final int MOD = 48;
  public static final int DESPDER = 50;
  public static final int MAYOR = 39;
  public static final int numeroEnt = 7;
  public static final int CCERRADO = 62;
  public static final int PCERRADO = 59;
  public static final int ENDIF = 22;
  public static final int ELSE = 21;
  public static final int out = 34;
  public static final int IGUALIGUAL = 43;
  public static final int WHILE = 23;
  public static final int FLOAT = 30;
  public static final int THEN = 20;
  public static final int not = 54;
  public static final int SWAP2 = 57;
  public static final int SWAP1 = 56;
  public static final int NAT = 53;
  public static final int numeroNat = 8;
  public static final int Call = 35;
  public static final int FALSE = 32;
  public static final int LLCERRADA = 64;
  public static final int DP = 55;
  public static final int VAR = 17;
  public static final int SUBPROGRAMS = 18;
  public static final int digito = 4;
  public static final int DO = 24;
  public static final int PYC = 67;
}

